import type { Metadata } from "next";
import "./(main)/globals.css"
import { Lausanne } from "@/lib/FontFile";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${Lausanne.variable}`}>
      <body
        className={``}
      >
        {children}
      </body>
    </html>
  );
}
